source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'aws-sdk-core'
gem 'mime-types'
gem 'json'
gem 'haml'

group :development do
  gem 'pry'
end

group :development, :test do
  gem 'rspec'
end

group :test do
  gem 'capybara'
end
